name: moncash
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  shared_preferences: ^2.0.15
  curved_navigation_bar: ^1.0.3
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.otf
    - family: PoMedium
      fonts:
        - asset: fonts/PoMedium.otf
    - family: PoBold
      fonts:
        - asset: fonts/PoBold.otf
    - family: PoRegular
      fonts:
        - asset: fonts/PoRegular.otf